import * as CryptoJS from 'crypto-js';
export const Constants = {
  key: CryptoJS.enc.Utf8.parse('4512631236589784'),
  iv: CryptoJS.enc.Utf8.parse('4512631236589784'),
  process_list_title_en: 'Inventory processes list',
  process_creation_title_en: 'Inventory process creation',
  process_modification_title_en: 'Inventory process edition',
  step_creation_title_en: "Step creation",
  step_modification_title_en: "Step edition",
  dataSource_list_title_en: 'Data sources',
  dataSource_creation_title_en: "Data source creation",
  dataSource_modification_title_en: "Data source edition",
  process_details_title_en: 'Inventory process description',
  step_details_title_en: "Step description",
  field_details_title_en: 'Field description',
  process_archiving_confirmation_message_en:
    'Are you sure you want to archive this inventory process ?',
  default_label_en: 'Label',
  input_fields_en: 'Input fields',
  output_fields_en: "Output fields",
  configuration_en: 'Field configuration',
  archived_processes_en: 'Archives',
  dropdown_titile_en: 'DropDown',
  date_input_title_en: 'Date input',
  link_title_en: 'Link',
  file_output_title_en: 'File output',
  text_output_title_en: 'Text output',
  text_input_title_en: 'Text input field',
  checkboxes_title_en: 'Checkboxes',
  radio_title_en: 'Radio buttons',
  slider_title_en: 'Slider',
  file_input_title_en: 'File upload',
  typeFiles: ['Image', 'Document', 'Video'],
  imageType: 'Image',
  documentType: 'Document',
  videoType: 'Video',
  extensionImage: ['JPEG/JPG', 'PNG', 'SVG', 'TIF'],
  extensionDocuments: ['PDF', 'DOC/DOCX', 'TXT', 'XLS/XLSX'],
  extensionVideos: ['MP4', 'AVI', 'MOV', 'FLV'],

  typeInputs: ['Text', 'Password', 'Number', 'Phone number'],

  type_inputs_en: {
    text: 'Text',
    password: 'Password',
    number: 'Number',
    phone_number: 'Phone number',
  },
  no_next_step_available_en: 'No next step available',
  validationRegex: [
    'Number',
    'Alphanumeric',
    'Alphabetic',
    'Phone Number',
    'E-mail',
    'Decimal',
  ],
  dataSourceType: [
    'Public',
    'Basic authentication',
    'Token based authentication',
  ],
  listCategoryField: [
    { label: 'DropDown', value: 'DropdownInput' },
    { label: 'File upload', value: 'FileInput' },
    { label: 'Slider', value: 'SliderInput' },
    { label: 'Radio buttons', value: 'RadioButtons' },
    { label: 'Checkboxes', value: 'Checkboxes' },
    { label: 'Text input', value: 'TextInput' },
    { label: 'Date input', value: 'DateInput' },
    { label: 'Text output', value: 'TextOutput' },
    { label: 'File output', value: 'FileOutput' },
    { label: 'Link', value: 'LinkOutput' },
  ],
};

/**
 * Here you can find the displayed text in different locales
 */
